export type Story = {
  slug: string; topic: string; topics: string[]; title: string; summary: string;
  byline: string; image: string; bullets: string[]; leaning: 'Left' | 'Centre' | 'Right';
  balance: [number, number, number]; sources: { name: string; url: string; primary?: boolean }[];
};

export type Curator = { name: string; role: string; avatar: string };

export const stories: Story[] = [
  { slug:'blue-carbon-stores', topic:'Oceans', topics:['Oceans','Climate','Restoration'], title:'The quiet return of Europe’s great blue carbon stores', summary:'From Scotland to the Adriatic, conservationists are restoring seagrass meadows — and discovering how much life can return when the seabed is given room to recover.', byline:'Mara Velasquez', image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1400&q=85', bullets:['Seagrass restoration is accelerating across European coastal waters, with new projects moving from small trials to whole-bay recovery plans.','Healthy meadows lock away carbon in seabed sediments while sheltering juvenile fish and stabilising vulnerable shorelines.','Divers and autonomous cameras are recording stronger biodiversity gains than early models predicted in several restored sites.','Projects still face pressure from anchors, dredging, nutrient pollution and poor water quality beyond restoration boundaries.','Researchers say long-term legal protection and local stewardship will determine whether the returning meadows survive.'], leaning:'Centre', balance:[28,58,14], sources:[{name:'UNEP — Seagrass ecosystems',url:'https://www.unep.org/resources/report/out-blue-value-seagrasses-environment-and-people',primary:true},{name:'The Guardian — Seagrass coverage',url:'https://www.theguardian.com/environment/seagrass'},{name:'Oceanographic — Blue carbon',url:'https://oceanographicmagazine.com/'}]},
  { slug:'elephant-corridor', topic:'Wildlife', topics:['Wildlife','Communities','Land use'], title:'A new corridor gives elephants room to roam', summary:'A community-led agreement is reconnecting fragmented habitat while keeping farms and families at the center of the plan.', byline:'Nia Okafor', image:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1200&q=85', bullets:['Neighbouring conservancies agreed to protect a migration route between two reserves after three years of community negotiation.','The plan funds crop-protection fencing, early-warning systems and rapid-response teams for farms closest to the corridor.','Landholders will receive annual conservation payments tied to keeping key pathways open and avoiding new barriers.','Researchers will monitor elephant movements and conflict reports to measure whether the corridor works over the next five years.','Community leaders say reliable benefits for families are essential if the agreement is to outlast its first funding cycle.'], leaning:'Centre', balance:[22,64,14], sources:[{name:'IUCN — African elephant',url:'https://www.iucn.org/our-work/topic/wildlife',primary:true},{name:'WWF — Elephant conservation',url:'https://www.worldwildlife.org/species/elephant'},{name:'Mongabay — Elephants',url:'https://news.mongabay.com/list/elephants/'}]},
  { slug:'forest-guardians', topic:'Forests', topics:['Forests','Indigenous affairs','Technology'], title:'The forest guardians mapping what satellites miss', summary:'Indigenous monitors are pairing generations of knowledge with new tools to protect one of the Amazon’s most threatened frontiers.', byline:'Jon Bell', image:'https://images.unsplash.com/photo-1653149875988-4fc5dff7a2cf?auto=format&fit=crop&w=1200&q=85', bullets:['Local patrols document illegal clearing and new access roads before damage appears in official satellite-alert systems.','Community-held drone imagery is helping authorities build stronger enforcement cases against organised land grabbing.','Monitors combine technical evidence with detailed knowledge of seasonal rivers, trails and places of cultural importance.','Weak communications infrastructure and personal safety risks continue to limit how quickly evidence can reach investigators.','Advocates say secure land rights and consistent state enforcement remain more important than technology alone.'], leaning:'Left', balance:[61,31,8], sources:[{name:'Global Forest Watch',url:'https://www.globalforestwatch.org/',primary:true},{name:'Reuters — Amazon rainforest',url:'https://www.reuters.com/world/americas/'},{name:'Mongabay — Amazon',url:'https://news.mongabay.com/list/amazon/'}]},
  { slug:'river-runs-free', topic:'Freshwater', topics:['Freshwater','Fish','Restoration'], title:'When a river runs free again', summary:'Two years after a century-old dam came down, salmon are returning to tributaries that had been out of reach for generations.', byline:'Avery Chen', image:'https://images.unsplash.com/photo-1510682406919-5e9caf2cf3d7?auto=format&fit=crop&w=1200&q=85', bullets:['Monitoring teams recorded adult salmon upstream of the former dam site during the first full migration season after removal.','Sediment released during demolition is settling and rebuilding banks faster than early engineering models predicted.','Cold-water tributaries are becoming accessible refuges as summer temperatures rise in the river’s lower reaches.','Tribal nations are leading long-term monitoring, native planting and the restoration of culturally important fishing sites.','Scientists caution that recovering a river system takes decades, even when the first biological signs are encouraging.'], leaning:'Centre', balance:[34,51,15], sources:[{name:'NOAA — Fish passage',url:'https://www.fisheries.noaa.gov/national/habitat-conservation/fish-passage',primary:true},{name:'AP — Dam removal',url:'https://apnews.com/hub/environment'},{name:'National Geographic — Rivers',url:'https://www.nationalgeographic.com/environment/'}]},
  { slug:'peatland-success-story', topic:'Land & climate', topics:['Wetlands','Climate','Policy'], title:'Can peatlands become the next climate success story?', summary:'The overlooked landscapes hold twice as much carbon as the world’s forests. A wave of restoration projects is finally matching their scale.', byline:'Leila Hart', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=1200&q=85', bullets:['Drained peat emits carbon continuously and becomes increasingly vulnerable to severe fires during hot, dry weather.','Governments are beginning to fund rewetting at landscape scale rather than treating sites as isolated conservation projects.','Restoration teams block drainage channels, re-establish native mosses and measure whether water tables remain stable year-round.','Farmers and rural communities need long-term incentives and practical alternatives to drainage-dependent land uses.','Specialists warn that damaged peat can take decades to recover, making protection of intact sites the immediate priority.'], leaning:'Left', balance:[54,37,9], sources:[{name:'UNEP — Global Peatlands Initiative',url:'https://www.unep.org/explore-topics/ecosystems-and-biodiversity/what-we-do/global-peatlands-initiative',primary:true},{name:'BBC — Peatlands',url:'https://www.bbc.com/future/article/20210604-the-bogs-that-store-carbon'},{name:'Carbon Brief',url:'https://www.carbonbrief.org/'}]},
  { slug:'urban-seed-banks', topic:'Solutions', topics:['Cities','Plants','Adaptation'], title:'The seed banks preparing cities for a hotter future', summary:'Botanists are collecting resilient native plants today so tomorrow’s urban forests can survive longer, drier summers.', byline:'Noah Reyes', image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85', bullets:['Seed banks are prioritising heat- and drought-tolerant native plant populations from the warm edges of their current ranges.','Genetic diversity can help future street trees withstand unfamiliar temperatures, pests and irregular rainfall.','Urban foresters are testing mixed plantings so the loss of one species does not strip shade from entire neighbourhoods.','Seed collections are being paired with detailed origin data to help future growers match plants to changing conditions.','Experts warn that collecting seed is insurance, not a substitute for protecting living habitat and mature urban trees.'], leaning:'Centre', balance:[31,56,13], sources:[{name:'Kew — Millennium Seed Bank',url:'https://www.kew.org/science/collections-and-resources/research-facilities/millennium-seed-bank',primary:true},{name:'National Geographic — Seed banks',url:'https://www.nationalgeographic.com/environment/'},{name:'The Conversation — Urban forests',url:'https://theconversation.com/uk/topics/urban-forests-17657'}]},
  { slug:'wolves-find-way-home', topic:'Wildlife', topics:['Wildlife','Rewilding','Communities'], title:'Wolves are finding their way home — and rewriting the landscape', summary:'A new generation of coexistence projects is helping rural communities adapt as wolves return to parts of their former European range.', byline:'Sofia Marin', image:'https://images.unsplash.com/photo-1564466809058-bf4114d55352?auto=format&fit=crop&w=1200&q=85', bullets:['Wolf populations are expanding naturally into regions where they have been absent for more than a century.','Livestock losses remain locally significant even where the overall rate of predation is low.','Guardian dogs, night enclosures and rapid compensation are most effective when used together.','Ecologists are tracking changes in deer behaviour, browsing pressure and scavenger food webs.','Trust between communities and conservation agencies is emerging as the decisive factor in long-term coexistence.'], leaning:'Centre', balance:[35,47,18], sources:[{name:'IUCN — Large carnivores',url:'https://www.iucn.org/our-work/topic/wildlife',primary:true},{name:'BBC — Wolf conservation',url:'https://www.bbc.com/future/'},{name:'Rewilding Europe',url:'https://rewildingeurope.com/'}]},
  { slug:'coral-nurseries-heat', topic:'Oceans', topics:['Oceans','Coral reefs','Climate'], title:'Coral nurseries face their hardest test yet', summary:'Restoration teams are changing what they grow and where they plant as repeated marine heatwaves reshape the rules of reef recovery.', byline:'Imani Brooks', image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=1200&q=85', bullets:['Marine heatwaves are arriving too frequently for conventional coral-restoration timelines.','Nurseries are increasing genetic diversity instead of relying on a few fast-growing fragments.','Some teams are prioritising naturally heat-tolerant colonies while avoiding a single “super coral” strategy.','Restored patches can still support fish and local livelihoods even when full historical recovery is unlikely.','Researchers stress that reef restoration cannot compensate for continued greenhouse-gas emissions.'], leaning:'Left', balance:[58,34,8], sources:[{name:'NOAA — Coral restoration',url:'https://www.fisheries.noaa.gov/national/habitat-conservation/restoring-coral-reefs',primary:true},{name:'The Conversation — Coral reefs',url:'https://theconversation.com/uk/topics/coral-reefs-2206'},{name:'Oceanographic',url:'https://oceanographicmagazine.com/'}]},
  { slug:'forest-fire-recovery', topic:'Forests', topics:['Forests','Wildfire','Restoration'], title:'After the fire, a debate over what a forest should become', summary:'Foresters are moving beyond blanket replanting as hotter fires force difficult choices about the future of burned landscapes.', byline:'Theo Grant', image:'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=85', bullets:['High-severity fires are leaving some landscapes without nearby seed sources for natural recovery.','Dense replanting can recreate vulnerable forests if future heat and drought are ignored.','Managers are testing mixed species, wider spacing and assisted migration from warmer regions.','Dead wood provides essential habitat and nutrients but can complicate public perceptions of recovery.','The central debate is shifting from recreating the past to sustaining functioning ecosystems in the future.'], leaning:'Centre', balance:[30,55,15], sources:[{name:'FAO — Forest fire management',url:'https://www.fao.org/forestry/wildfire-management/en',primary:true},{name:'Science — Forest recovery',url:'https://www.science.org/topic/forestry'},{name:'Mongabay — Wildfires',url:'https://news.mongabay.com/list/wildfires/'}]},
  { slug:'beavers-urban-rivers', topic:'Freshwater', topics:['Freshwater','Wildlife','Cities'], title:'The beavers quietly engineering urban rivers', summary:'Cities are learning to live with a returning ecosystem engineer whose dams can cool streams, hold water and occasionally flood a footpath.', byline:'Elliot Price', image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85', bullets:['Beaver dams slow stormwater and create cooler wetland habitat in urban catchments.','New wetlands can support amphibians, fish, insects and waterbirds within a single season.','Flow devices and protective fencing can reduce flooding risks without removing animals.','Successful projects include residents in monitoring water levels and reporting emerging conflicts.','City planners are beginning to treat beaver activity as green infrastructure rather than simply wildlife management.'], leaning:'Centre', balance:[29,57,14], sources:[{name:'IUCN — Beaver restoration',url:'https://www.iucn.org/our-work/topic/wildlife',primary:true},{name:'The Wildlife Trusts — Beavers',url:'https://www.wildlifetrusts.org/saving-species/beavers'},{name:'BBC Wildlife',url:'https://www.discoverwildlife.com/'}]},
  { slug:'grasslands-carbon-blindspot', topic:'Land & climate', topics:['Grasslands','Climate','Agriculture'], title:'The carbon landscape hiding beneath our feet', summary:'Grasslands store much of their carbon underground, yet conservation funding still tends to favour the places where carbon is easiest to see.', byline:'Priya Shah', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=1200&q=85', bullets:['Healthy grasslands hold large carbon reserves in deep roots and soil organic matter.','Ploughing and conversion can release stores accumulated over decades or centuries.','Well-managed grazing can support biodiversity, but outcomes vary sharply with rainfall, soil and stocking density.','Carbon markets struggle to measure slow, variable changes below ground with confidence.','Conservationists argue that protecting intact grassland is cheaper and more reliable than rebuilding degraded soils.'], leaning:'Centre', balance:[37,49,14], sources:[{name:'UNCCD — Grasslands',url:'https://www.unccd.int/',primary:true},{name:'Carbon Brief — Land',url:'https://www.carbonbrief.org/category/food-and-farming/'},{name:'FAO — Grassland systems',url:'https://www.fao.org/grasslands/en/'}]},
  { slug:'pangolin-trafficking-routes', topic:'Wildlife', topics:['Wildlife','Crime','Policy'], title:'New data reveals how pangolin trafficking routes are changing', summary:'A cross-border intelligence project suggests traffickers are fragmenting shipments and shifting transit hubs to avoid detection.', byline:'Amara Diallo', image:'https://images.unsplash.com/photo-1535338454770-8be927b5a00b?auto=format&fit=crop&w=1200&q=85', bullets:['Smaller shipments are replacing some high-volume routes as enforcement improves at major ports.','Investigators are combining financial records, seizure data and phone evidence across jurisdictions.','Rescue centres face capacity pressures as more live animals are intercepted.','Conservation groups want prosecutions to target organisers and money flows, not only low-level couriers.','Demand reduction and habitat protection remain essential alongside stronger border enforcement.'], leaning:'Centre', balance:[33,52,15], sources:[{name:'CITES — Pangolins',url:'https://cites.org/eng/prog/pangolin',primary:true},{name:'TRAFFIC',url:'https://www.traffic.org/'},{name:'Mongabay — Wildlife trade',url:'https://news.mongabay.com/list/wildlife-trade/'}]},
  { slug:'kelp-forest-recovery', topic:'Oceans', topics:['Oceans','Kelp','Restoration'], title:'A coastline bets on the return of its underwater forests', summary:'Urchin control, predator recovery and kelp planting are being combined in an ambitious attempt to reverse decades of marine decline.', byline:'Mae Tanaka', image:'https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1200&q=85', bullets:['Kelp forests create complex habitat and support coastal fisheries, tourism and shoreline protection.','Exploding sea-urchin populations can turn productive reefs into long-lasting barren grounds.','Divers are reducing urchin density while hatcheries grow native kelp for targeted restoration.','Recovering predators may help maintain balance, but results differ between regions and reef types.','Teams are measuring ecological recovery alongside benefits for fishing communities and local businesses.'], leaning:'Centre', balance:[32,55,13], sources:[{name:'UNEP — Kelp forests',url:'https://www.unep.org/news-and-stories/story/kelp-forests-offer-hope-climate-biodiversity-and-coastal-communities',primary:true},{name:'NOAA — Kelp',url:'https://oceanservice.noaa.gov/facts/kelp.html'},{name:'Oceanographic',url:'https://oceanographicmagazine.com/'}]},
  { slug:'pollinator-highways', topic:'Solutions', topics:['Cities','Pollinators','Restoration'], title:'Cities stitch together new highways for pollinators', summary:'Road verges, roofs and pocket parks are being connected into flowering routes that help insects cross fragmented urban landscapes.', byline:'Grace Mensah', image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1200&q=85', bullets:['Connected patches allow insects to move between feeding, nesting and overwintering habitat.','Native plants with staggered flowering times provide food from early spring into autumn.','Reduced mowing often delivers greater benefits than expensive new infrastructure.','Monitoring shows that corridor quality matters more than simply counting planted sites.','Long-term maintenance budgets are essential to prevent diverse plantings reverting to short grass.'], leaning:'Centre', balance:[39,49,12], sources:[{name:'IUCN — Pollinators',url:'https://www.iucn.org/resources/issues-brief/pollinator-decline',primary:true},{name:'Buglife — B-Lines',url:'https://www.buglife.org.uk/our-work/b-lines/'},{name:'The Conversation — Pollinators',url:'https://theconversation.com/uk/topics/pollinators-2349'}]},
  { slug:'mangrove-insurance', topic:'Land & climate', topics:['Coasts','Climate','Communities'], title:'When mangroves become coastal insurance', summary:'New risk models are putting a financial value on the storm protection provided by living shorelines — with promising and uncomfortable consequences.', byline:'Rafael Costa', image:'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=85', bullets:['Mangrove roots reduce wave energy, trap sediment and lessen damage from storm surges.','Insurers and governments are testing resilience bonds that help fund restoration before disasters.','Financial valuation can unlock investment but risks overlooking cultural and ecological values.','Projects work best when local communities retain access, tenure and decision-making power.','Protection of existing mature mangroves remains more effective than replacing cleared habitat later.'], leaning:'Centre', balance:[41,46,13], sources:[{name:'World Bank — Mangroves',url:'https://www.worldbank.org/en/news/feature/2021/07/26/mangroves-are-vital-to-climate-resilience',primary:true},{name:'UNEP — Mangrove restoration',url:'https://www.unep.org/topics/ocean-seas-and-coasts/blue-ecosystems/mangroves'},{name:'Reuters — Sustainable finance',url:'https://www.reuters.com/sustainability/'}]},
  { slug:'cranes-return-wetlands', topic:'Freshwater', topics:['Freshwater','Birds','Restoration'], title:'Cranes return as a forgotten wetland wakes up', summary:'Water-level changes and patient habitat work have brought breeding cranes back to a floodplain once written off as lost.', byline:'Hannah Cole', image:'https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=1200&q=85', bullets:['Restoration reconnected seasonal floodwater to fields that had been intensively drained.','Shallow pools and wet grassland now support cranes, waders, amphibians and aquatic insects.','Farmers are being paid for water storage and lower-intensity management on flood-prone land.','Breeding success remains vulnerable to disturbance, drought and poorly timed water releases.','The project shows how flood management and biodiversity recovery can reinforce each other.'], leaning:'Centre', balance:[36,51,13], sources:[{name:'RSPB — Wetland restoration',url:'https://www.rspb.org.uk/helping-nature/what-we-do/protecting-species-and-habitats/wetlands',primary:true},{name:'BirdLife International',url:'https://www.birdlife.org/'},{name:'BBC Wildlife',url:'https://www.discoverwildlife.com/'}]},
  { slug:'gorilla-tourism-reset', topic:'Wildlife', topics:['Wildlife','Communities','Tourism'], title:'Mountain gorilla tourism is being rebuilt around local benefit', summary:'Conservation groups are testing a fairer tourism model that protects gorillas while keeping more income in the communities living beside their forest habitat.', byline:'Akello Namusoke', image:'https://images.unsplash.com/photo-1581281863883-2469417a1668?auto=format&fit=crop&w=1200&q=85', bullets:['Permit revenue remains central to gorilla protection, but communities closest to protected forests often receive only a small share of the money visitors bring.','New agreements direct more income towards locally owned guiding, accommodation, transport and conservation enterprises instead of concentrating benefits with outside operators.','Health rules remain strict because respiratory infections carried by people can spread quickly through small and closely related gorilla populations.','Researchers are comparing household income, attitudes towards conservation and gorilla health so that economic success is not mistaken for ecological success.','Community leaders say the model will endure only if land access, crop losses and decision-making power are addressed alongside tourism revenue.'], leaning:'Centre', balance:[32,53,15], sources:[{name:'IUCN: Great apes',url:'https://www.iucn.org/our-work/topic/wildlife',primary:true},{name:'WCS: Apes',url:'https://www.wcs.org/our-work/wildlife/apes'},{name:'WWF: Mountain gorillas',url:'https://www.worldwildlife.org/species/mountain-gorilla'}]},
  { slug:'sea-turtle-nests-heat', topic:'Oceans', topics:['Oceans','Wildlife','Climate'], title:'Hotter beaches are changing the future of sea turtles', summary:'Nest shading, careful relocation and long-term beach monitoring are helping conservationists respond as rising sand temperatures alter hatchling survival.', byline:'Mila Fernandez', image:'https://images.unsplash.com/photo-1607896477672-21ffa8e2b36e?auto=format&fit=crop&w=1200&q=85', bullets:['The temperature of incubating nests influences hatchling sex, so sustained warming can produce heavily skewed populations long before adult numbers visibly decline.','Teams are testing shade cloth, irrigation and selective nest relocation while trying to preserve the natural cues hatchlings need to reach the sea.','Moving every nest is neither practical nor desirable because handling can damage eggs and may reduce adaptation to changing local conditions.','Beach lighting, vehicles, erosion and coastal development compound the effects of heat by reducing the amount of safe nesting habitat available.','Scientists need decades of monitoring because sea turtles mature slowly and today’s hatchling imbalance may not appear in breeding populations for many years.'], leaning:'Centre', balance:[37,50,13], sources:[{name:'NOAA: Sea turtles',url:'https://www.fisheries.noaa.gov/sea-turtles',primary:true},{name:'IUCN: Marine turtles',url:'https://www.iucn-mtsg.org/'},{name:'Marine Conservation Society',url:'https://www.mcsuk.org/'}]},
  { slug:'oyster-reefs-comeback', topic:'Oceans', topics:['Oceans','Restoration','Fisheries'], title:'The complicated comeback of the oyster reef', summary:'Coastal restoration teams are rebuilding living reefs that filter water and shelter fish, while negotiating where harvest and habitat protection can coexist.', byline:'Caleb Wright', image:'https://images.unsplash.com/photo-1710671340602-c50b441d2184?auto=format&fit=crop&w=1200&q=85', bullets:['Centuries of harvesting, dredging and poor water quality have removed most historic oyster reefs from many temperate estuaries and coastal bays.','Restoration projects place clean shell or limestone at suitable depths, then seed those foundations with juvenile oysters raised in specialist hatcheries.','A mature reef can filter large volumes of water, create complex fish habitat and reduce wave energy along vulnerable shorelines.','Disease, sediment and repeated harvest can erase early gains, so projects increasingly use protected sanctuary reefs alongside carefully managed commercial areas.','Success is measured through oyster survival, reef height, water quality and the return of associated fish and invertebrate communities over several years.'], leaning:'Centre', balance:[30,57,13], sources:[{name:'NOAA: Oyster reef restoration',url:'https://www.fisheries.noaa.gov/national/habitat-conservation/oyster-reef-habitat',primary:true},{name:'Chesapeake Bay Program',url:'https://www.chesapeakebay.net/issues/whats-at-risk/oysters'},{name:'The Nature Conservancy: Oysters',url:'https://www.nature.org/en-us/about-us/where-we-work/united-states/oyster-restoration/'}]},
  { slug:'prairie-restoration-drought', topic:'Land & climate', topics:['Grasslands','Restoration','Climate'], title:'Prairie restoration faces a new test from drought', summary:'Restored grasslands are being designed for greater diversity as hotter, less predictable seasons expose the limits of simple seed mixes.', byline:'June Redbird', image:'https://images.unsplash.com/photo-1626867589307-61e208503794?auto=format&fit=crop&w=1200&q=85', bullets:['Many early restoration projects relied on a narrow mix of grasses that established quickly but lacked the diversity of intact prairie communities.','Teams are now adding deep-rooted flowers, sedges and locally adapted seed collected across different moisture and temperature conditions.','Patchy germination during drought can look like failure in the first year even when dormant seed and perennial roots remain viable below ground.','Prescribed fire and grazing still play important roles, but managers are adjusting timing so stressed plants have enough opportunity to recover.','Long-term plots are revealing which combinations support pollinators, hold soil and maintain growth when rainfall arrives in shorter, more intense bursts.'], leaning:'Centre', balance:[35,51,14], sources:[{name:'USDA NRCS: Grasslands',url:'https://www.nrcs.usda.gov/conservation-basics/natural-resource-concerns/land/grasslands',primary:true},{name:'The Nature Conservancy: Grasslands',url:'https://www.nature.org/en-us/what-we-do/our-priorities/protect-water-and-land/land-and-water-stories/grasslands/'},{name:'Audubon: Grassland conservation',url:'https://www.audubon.org/conservation/grasslands'}]},
  { slug:'snow-leopard-insurance', topic:'Wildlife', topics:['Wildlife','Communities','Mountains'], title:'Livestock insurance is changing snow leopard conservation', summary:'Community-managed funds are compensating herders for verified losses and rewarding villages that keep both predators and prey alive in high mountain landscapes.', byline:'Tenzin Dorje', image:'https://images.unsplash.com/photo-1698578153726-2114cac67753?auto=format&fit=crop&w=1200&q=85', bullets:['A single snow leopard attack can wipe out a significant share of a household’s annual income, creating strong pressure for retaliatory killing.','Village insurance schemes combine household premiums with conservation funding and pay quickly when trained local assessors confirm a livestock loss.','Some programmes add annual bonuses when no snow leopards are killed, linking collective benefit to the survival of predators across shared grazing land.','Stronger corrals and better herding reduce risk, but they require materials, labour and designs that work during severe winter weather.','Conservationists are tracking whether compensation remains affordable and trusted after outside grants decline, because delayed payments can rapidly undermine participation.'], leaning:'Centre', balance:[34,52,14], sources:[{name:'Snow Leopard Trust',url:'https://snowleopard.org/',primary:true},{name:'IUCN: Snow leopard',url:'https://www.iucnredlist.org/'},{name:'WWF: Snow leopards',url:'https://www.worldwildlife.org/species/snow-leopard'}]},
  { slug:'lights-out-migration', topic:'Solutions', topics:['Birds','Cities','Technology'], title:'Cities are dimming their skylines for migrating birds', summary:'Temporary lights-out programmes are using weather radar and migration forecasts to reduce deadly collisions during the busiest nights of spring and autumn.', byline:'Erin Park', image:'https://images.unsplash.com/photo-1520792532857-293bd046307a?auto=format&fit=crop&w=1200&q=85', bullets:['Many migratory birds travel at night and can become disoriented by bright buildings, especially during low cloud and poor visibility.','Forecasting tools combine radar, weather and historical migration data to identify the handful of nights when switching off lights can have the greatest benefit.','Building owners are asked to turn off decorative lighting, close blinds and reduce unnecessary illumination after midnight during peak movement.','Volunteers collect and identify birds beneath high-risk buildings, creating evidence that helps cities target retrofits and evaluate whether voluntary schemes work.','Campaigners say permanent building standards are still needed because short alerts cannot address every migration night or every dangerous glass facade.'], leaning:'Centre', balance:[40,48,12], sources:[{name:'Audubon: Lights Out',url:'https://www.audubon.org/our-work/cities-and-towns/lights-out',primary:true},{name:'Cornell Lab: BirdCast',url:'https://birdcast.info/'},{name:'US Fish and Wildlife Service',url:'https://www.fws.gov/'}]},
  { slug:'shark-nursery-protection', topic:'Oceans', topics:['Oceans','Wildlife','Policy'], title:'Young sharks are reshaping marine protection', summary:'Researchers are mapping shallow nursery grounds so fisheries rules and coastal development decisions can protect sharks during their most vulnerable life stage.', byline:'Amir Patel', image:'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=1200&q=85', bullets:['Many shark species use warm, productive bays as nurseries where young animals can find food and avoid larger predators during their first years.','Acoustic tags and environmental DNA are revealing nursery areas that conventional surveys missed, including sites close to heavily developed coastlines.','Seasonal fishing restrictions can reduce accidental catch without closing entire regions, but only when boundaries match the animals’ actual movements.','Pollution, dredging and the loss of mangroves or seagrass can damage nursery function even when direct shark fishing is tightly controlled.','Researchers want nursery maps built into marine planning early, before ports, reclamation projects and coastal infrastructure make protection more difficult.'], leaning:'Centre', balance:[33,54,13], sources:[{name:'IUCN Shark Specialist Group',url:'https://www.iucnssg.org/',primary:true},{name:'NOAA: Shark conservation',url:'https://www.fisheries.noaa.gov/topic/sharks'},{name:'The Shark Trust',url:'https://www.sharktrust.org/'}]},
  { slug:'islands-without-rats', topic:'Wildlife', topics:['Wildlife','Islands','Restoration'], title:'What happens when an island is finally free of rats?', summary:'Years after invasive rats are removed, seabirds, reptiles and coastal plants are returning, revealing how recovery spreads from land into the surrounding sea.', byline:'Moana Kealoha', image:'https://images.unsplash.com/photo-1644321983774-89061710b5f2?auto=format&fit=crop&w=1200&q=85', bullets:['Introduced rats eat eggs, chicks, reptiles, insects and seeds, disrupting island food webs that evolved without mammalian predators.','Successful eradications require every bait station and monitoring device to work across cliffs, settlements and difficult terrain during a tightly planned operation.','Seabird colonies often recover first, carrying marine nutrients onto land through guano and enriching soils that support plants and invertebrates.','Biosecurity becomes the permanent task after eradication, with ports, boats and cargo inspected so a single pregnant rat cannot restart the invasion.','Local consent is essential because eradication methods involve real risks and because residents are responsible for maintaining surveillance long after specialists leave.'], leaning:'Centre', balance:[36,51,13], sources:[{name:'Island Conservation',url:'https://www.islandconservation.org/',primary:true},{name:'BirdLife International: Islands',url:'https://www.birdlife.org/'},{name:'IUCN: Invasive species',url:'https://www.iucn.org/our-work/topic/invasive-alien-species'}]},
  { slug:'fungi-restoration-network', topic:'Forests', topics:['Forests','Soil','Restoration'], title:'Restoration is learning to work with the fungi underground', summary:'Ecologists are paying closer attention to mycorrhizal networks that help plants find water and nutrients, especially on severely degraded land.', byline:'Elena Rossi', image:'https://images.unsplash.com/photo-1629457442277-918387fec70c?auto=format&fit=crop&w=1200&q=85', bullets:['Most land plants form partnerships with fungi that extend beyond their roots and exchange soil nutrients for sugars produced through photosynthesis.','Mined, compacted or intensively farmed soils may lack the fungal communities needed for native seedlings to survive after they are planted.','Restoration teams are testing small amounts of locally sourced soil inoculum, nursery treatments and planting near surviving habitat that can act as a reservoir.','Introducing fungi without careful screening can spread pathogens or poorly matched species, so researchers are resisting the rush towards universal commercial products.','The strongest evidence supports rebuilding whole soil communities and reducing disturbance rather than treating one fungal strain as a simple technological fix.'], leaning:'Centre', balance:[42,47,11], sources:[{name:'Kew: State of the World’s Plants and Fungi',url:'https://www.kew.org/science/our-science/projects/state-of-the-worlds-plants-and-fungi',primary:true},{name:'Society for Ecological Restoration',url:'https://www.ser.org/'},{name:'Nature: Soil ecology',url:'https://www.nature.com/subjects/soil-ecology'}]},
  { slug:'urban-wetlands-floods', topic:'Freshwater', topics:['Freshwater','Cities','Climate'], title:'Urban wetlands are becoming part of the flood plan', summary:'Cities are restoring marshes and floodplains as working infrastructure that can hold stormwater, cool neighbourhoods and create habitat close to home.', byline:'Samira Okoye', image:'https://images.unsplash.com/photo-1786795468102-84cd1ac41cd8?auto=format&fit=crop&w=1200&q=85', bullets:['Hard flood defences move water quickly, while wetlands slow and temporarily store it, reducing pressure on drains and downstream communities during intense rain.','Restored sites can also lower local temperatures, filter pollution and provide accessible green space in neighbourhoods that have historically received less investment.','Engineers need accurate models because a wetland cannot absorb unlimited water and may fail if development continues across the wider catchment.','Projects work best when maintenance, public access, mosquito management and habitat goals are agreed with residents before earthworks begin.','City planners are starting to measure avoided flood damage alongside biodiversity, health and recreation benefits when comparing wetlands with conventional infrastructure.'], leaning:'Centre', balance:[39,48,13], sources:[{name:'Ramsar Convention: Urban wetlands',url:'https://www.ramsar.org/',primary:true},{name:'UN-Habitat: Nature-based solutions',url:'https://unhabitat.org/'},{name:'World Bank: Urban resilience',url:'https://www.worldbank.org/en/topic/urbandevelopment'}]},
];

export const curators: Curator[] = [
  { name: 'Adam Barlow', role: 'Executive Director', avatar: '/team/adam-barlow.jpg' },
  { name: 'Lucy Boddam-Whetham', role: 'Director, Training & Operations', avatar: '/team/lucy-boddam-whetham.jpg' },
  { name: 'Léa Kaplani', role: 'WildLearning Specialist', avatar: '/team/lea-kaplani.png' },
  { name: 'Zoe Melvin', role: 'WildLearning Specialist', avatar: '/team/zoe-melvin.jpg' },
  { name: 'Ali Skeats', role: 'WildLearning Specialist Manager', avatar: '/team/ali-skeats.png' },
  { name: 'Matt Barker', role: 'Communications and Engagement Specialist', avatar: '/team/matt-barker.jpg' },
];

const curatorAssignments = [4,1,5,2,0,3,2,0,4,5,3,1,5,3,1,0,2,4,1,4,2,3,5,0,3,0];
stories.forEach((story, index) => { story.byline = curators[curatorAssignments[index % curatorAssignments.length]].name; });

const imageOverrides: Record<string, string> = {
  'blue-carbon-stores': 'https://images.unsplash.com/photo-1629215833350-8ddcec7e1153?auto=format&fit=crop&w=1400&q=85',
  'peatland-success-story': 'https://images.unsplash.com/photo-1771232274335-fb94d93d1e2f?auto=format&fit=crop&w=1200&q=85',
  'urban-seed-banks': 'https://images.unsplash.com/photo-1769149941429-5474eae5a727?auto=format&fit=crop&w=1200&q=85',
  'wolves-find-way-home': 'https://images.unsplash.com/photo-1588167056547-c183313da47c?auto=format&fit=crop&w=1200&q=85',
  'forest-fire-recovery': 'https://images.unsplash.com/photo-1621525332263-6643c2ed0fa3?auto=format&fit=crop&w=1200&q=85',
  'beavers-urban-rivers': 'https://images.unsplash.com/photo-1727883760212-655dc564a99c?auto=format&fit=crop&w=1200&q=85',
  'grasslands-carbon-blindspot': 'https://images.unsplash.com/photo-1624392241386-f5da1961fee0?auto=format&fit=crop&w=1200&q=85',
  'pangolin-trafficking-routes': 'https://images.unsplash.com/photo-1754414433737-d69734c7d58a?auto=format&fit=crop&w=1200&q=85',
  'kelp-forest-recovery': 'https://images.unsplash.com/photo-1745917784526-fbad88531db1?auto=format&fit=crop&w=1200&q=85',
  'pollinator-highways': 'https://images.unsplash.com/photo-1550170139-ed6b5e6b4c38?auto=format&fit=crop&w=1200&q=85',
  'mangrove-insurance': 'https://images.unsplash.com/photo-1589556183130-530470785fab?auto=format&fit=crop&w=1200&q=85',
  'cranes-return-wetlands': 'https://images.unsplash.com/photo-1577870142472-476ba8111ef1?auto=format&fit=crop&w=1200&q=85',
};

const pointContext: Record<string, string[]> = {
  Oceans: ['Researchers are comparing several sites so local improvements are not mistaken for a wider recovery.', 'The outcome depends on water quality and activity across the whole coastal system, not only inside the project boundary.', 'Monitoring combines species counts with physical measures such as temperature, depth, sediment and wave exposure.', 'Teams still need stable finance, clear rules and practical enforcement after the first restoration funding ends.', 'The next phase will test whether ecological gains continue through extreme weather and changing ocean conditions.'],
  Wildlife: ['Population trends are being checked alongside local experience so isolated sightings are not treated as proof of recovery.', 'The practical costs and benefits for people living closest to wildlife remain central to whether the approach lasts.', 'Researchers are tracking behaviour, survival and habitat use rather than relying on a single headline population estimate.', 'Delivery depends on trusted local institutions, predictable funding and a credible response when conflict occurs.', 'Long-term success means keeping habitat connected while maintaining community consent and livelihoods.'],
  Forests: ['Field evidence is being compared with remote sensing so changes beneath the canopy are not overlooked.', 'Recovery depends on soil, water, fire and surrounding land use as much as the number of trees planted.', 'Teams are measuring species composition and structure instead of treating simple tree cover as the only result.', 'Rights, safety and reliable long-term funding shape whether local monitoring can continue after a pilot ends.', 'Researchers will need years of data to separate durable recovery from short-lived growth after disturbance.'],
  Freshwater: ['Results are being measured across the wider catchment because changes upstream can quickly reverse progress at one site.', 'Water flow, temperature and sediment are tracked alongside wildlife so the physical system and its species are assessed together.', 'Local landholders and water users influence the outcome through everyday decisions beyond the formal project boundary.', 'Maintenance and monitoring must continue through both drought and flood conditions, not only during favourable seasons.', 'The strongest test is whether ecological recovery and community benefits remain visible after initial funding ends.'],
  'Land & climate': ['Researchers are using long-term field plots because changes in soil and vegetation can take years to become reliable.', 'Climate benefits are being assessed alongside biodiversity, water and livelihoods rather than reduced to one carbon estimate.', 'Landholder incentives and secure local participation determine whether management changes survive beyond a short contract.', 'Projects must account for leakage, where pressure is displaced to nearby land instead of genuinely reduced.', 'The next stage is to test whether results endure through drought, fire and shifting agricultural markets.'],
  Solutions: ['Teams are measuring ecological outcomes, not just the number of sites, plants or devices delivered.', 'The approach works best when maintenance responsibilities and funding are agreed before the first visible results appear.', 'Local knowledge helps identify practical barriers that a technically promising pilot may otherwise miss.', 'Researchers are looking for unintended effects and unequal access alongside the headline conservation benefit.', 'Scaling the idea will require evidence that it remains effective, affordable and locally supported in different settings.'],
};

export const cleanCopy = (text: string) => text.replace(/\s*—\s*/g, ', ');
export const storyImage = (story: Story) => imageOverrides[story.slug] ?? story.image;
export const storyOverview = (story: Story) => [
  cleanCopy(story.summary),
  `${cleanCopy(story.bullets[0])} ${cleanCopy(story.bullets[1])}`,
];
export const expandedBullet = (story: Story, bullet: string, index: number) => {
  const context = pointContext[story.topic] ?? pointContext.Solutions;
  return `${cleanCopy(bullet)} ${context[index]}`;
};

export const getStory = (slug: string) => stories.find((story) => story.slug === slug);

export const slugify = (value: string) => value
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase()
  .replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

export const topicSlug = (topic: string) => slugify(topic);
export const authorSlug = (author: string) => slugify(author);

export const allTopics = Array.from(new Set(stories.flatMap((story) => [story.topic, ...story.topics])));
export const allAuthors = curators.map((curator) => curator.name);

export const getTopic = (slug: string) => allTopics.find((topic) => topicSlug(topic) === slug);
export const getAuthor = (slug: string) => allAuthors.find((author) => authorSlug(author) === slug);
export const getCurator = (name: string) => curators.find((curator) => curator.name === name);
