export type Story = {
  slug: string; topic: string; topics: string[]; title: string; summary: string;
  byline: string; image: string; bullets: string[]; leaning: 'Left' | 'Centre' | 'Right';
  balance: [number, number, number]; sources: { name: string; url: string; primary?: boolean }[];
};

export const stories: Story[] = [
  { slug:'blue-carbon-stores', topic:'Oceans', topics:['Oceans','Climate','Restoration'], title:'The quiet return of Europe’s great blue carbon stores', summary:'From Scotland to the Adriatic, conservationists are restoring seagrass meadows — and discovering how much life can return when the seabed is given room to recover.', byline:'Mara Velasquez', image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1400&q=85', bullets:['Seagrass restoration is accelerating across European coastal waters.','Healthy meadows lock away carbon while sheltering juvenile fish and stabilising shorelines.','Projects still face pressure from anchors, dredging and poor water quality.'], leaning:'Centre', balance:[28,58,14], sources:[{name:'UNEP — Seagrass ecosystems',url:'https://www.unep.org/resources/report/out-blue-value-seagrasses-environment-and-people',primary:true},{name:'The Guardian — Seagrass coverage',url:'https://www.theguardian.com/environment/seagrass'},{name:'Oceanographic — Blue carbon',url:'https://oceanographicmagazine.com/'}]},
  { slug:'elephant-corridor', topic:'Wildlife', topics:['Wildlife','Communities','Land use'], title:'A new corridor gives elephants room to roam', summary:'A community-led agreement is reconnecting fragmented habitat while keeping farms and families at the center of the plan.', byline:'Nia Okafor', image:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1200&q=85', bullets:['Neighbouring conservancies agreed to protect a migration route between two reserves.','The plan funds crop protection and rapid-response teams for nearby farms.','Researchers will monitor whether the corridor reduces conflict over the next five years.'], leaning:'Centre', balance:[22,64,14], sources:[{name:'IUCN — African elephant',url:'https://www.iucn.org/our-work/topic/wildlife',primary:true},{name:'WWF — Elephant conservation',url:'https://www.worldwildlife.org/species/elephant'},{name:'Mongabay — Elephants',url:'https://news.mongabay.com/list/elephants/'}]},
  { slug:'forest-guardians', topic:'Forests', topics:['Forests','Indigenous affairs','Technology'], title:'The forest guardians mapping what satellites miss', summary:'Indigenous monitors are pairing generations of knowledge with new tools to protect one of the Amazon’s most threatened frontiers.', byline:'Jon Bell', image:'https://images.unsplash.com/photo-1653149875988-4fc5dff7a2cf?auto=format&fit=crop&w=1200&q=85', bullets:['Local patrols document illegal clearing before it appears in official satellite alerts.','Community-held data is helping authorities build stronger enforcement cases.','Advocates say land rights remain more important than technology alone.'], leaning:'Left', balance:[61,31,8], sources:[{name:'Global Forest Watch',url:'https://www.globalforestwatch.org/',primary:true},{name:'Reuters — Amazon rainforest',url:'https://www.reuters.com/world/americas/'},{name:'Mongabay — Amazon',url:'https://news.mongabay.com/list/amazon/'}]},
  { slug:'river-runs-free', topic:'Freshwater', topics:['Freshwater','Fish','Restoration'], title:'When a river runs free again', summary:'Two years after a century-old dam came down, salmon are returning to tributaries that had been out of reach for generations.', byline:'Avery Chen', image:'https://images.unsplash.com/photo-1510682406919-5e9caf2cf3d7?auto=format&fit=crop&w=1200&q=85', bullets:['Monitoring teams recorded salmon upstream of the former dam site.','Sediment released during removal is settling faster than early models predicted.','Tribal nations are leading long-term monitoring and habitat repair.'], leaning:'Centre', balance:[34,51,15], sources:[{name:'NOAA — Fish passage',url:'https://www.fisheries.noaa.gov/national/habitat-conservation/fish-passage',primary:true},{name:'AP — Dam removal',url:'https://apnews.com/hub/environment'},{name:'National Geographic — Rivers',url:'https://www.nationalgeographic.com/environment/'}]},
  { slug:'peatland-success-story', topic:'Land & climate', topics:['Wetlands','Climate','Policy'], title:'Can peatlands become the next climate success story?', summary:'The overlooked landscapes hold twice as much carbon as the world’s forests. A wave of restoration projects is finally matching their scale.', byline:'Leila Hart', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=1200&q=85', bullets:['Drained peat emits carbon and becomes increasingly vulnerable to fire.','Governments are beginning to fund rewetting at landscape scale.','Farmers need long-term incentives for restoration to endure.'], leaning:'Left', balance:[54,37,9], sources:[{name:'UNEP — Global Peatlands Initiative',url:'https://www.unep.org/explore-topics/ecosystems-and-biodiversity/what-we-do/global-peatlands-initiative',primary:true},{name:'BBC — Peatlands',url:'https://www.bbc.com/future/article/20210604-the-bogs-that-store-carbon'},{name:'Carbon Brief',url:'https://www.carbonbrief.org/'}]},
  { slug:'urban-seed-banks', topic:'Solutions', topics:['Cities','Plants','Adaptation'], title:'The seed banks preparing cities for a hotter future', summary:'Botanists are collecting resilient native plants today so tomorrow’s urban forests can survive longer, drier summers.', byline:'Noah Reyes', image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85', bullets:['Seed banks are prioritising heat- and drought-tolerant native populations.','Genetic diversity can help future street trees withstand unfamiliar conditions.','Experts warn that collecting seed is no substitute for protecting habitat.'], leaning:'Centre', balance:[31,56,13], sources:[{name:'Kew — Millennium Seed Bank',url:'https://www.kew.org/science/collections-and-resources/research-facilities/millennium-seed-bank',primary:true},{name:'National Geographic — Seed banks',url:'https://www.nationalgeographic.com/environment/'},{name:'The Conversation — Urban forests',url:'https://theconversation.com/uk/topics/urban-forests-17657'}]},
];

export const getStory = (slug: string) => stories.find((story) => story.slug === slug);
